import path from 'node:path';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { discoverDisciplines, toSidebarId } from './src/disciplines';

const DOCS_DIR = path.join(__dirname, 'docs');

const disciplines = discoverDisciplines(DOCS_DIR);

const sidebars: SidebarsConfig = {
  ...Object.fromEntries(
    disciplines.map((d) => [d.sidebarId, [{ type: 'autogenerated', dirName: d.dirName }]])
  ),
  communitySidebar: [{ type: 'autogenerated', dirName: 'community' }],
};

export default sidebars;
