import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  productSidebar: [{ type: 'autogenerated', dirName: 'product' }],
  integrationSidebar: [{ type: 'autogenerated', dirName: 'integration' }],
  uxSidebar: [{ type: 'autogenerated', dirName: 'ux' }],
  projectManagementSidebar: [{ type: 'autogenerated', dirName: 'project-management' }],
};

export default sidebars;
